### ISSUE TITLE
Open Source this repo

### ISSUE THREAD

**Issue by robb-j** [digitalinteraction/pdc#2]
**Tasks**

- [x] Check through code and tidy things up
- [x] Create project README.md
- [x] Document dev setup in DEVELOPMENT.md 
- [ ] Explain devops setup in OPERATIONS.md
- [x] Make public
